### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by BradleyGBrandt** [rdzhaoxin/bionic-reading-docs#1]
I tried multiple fonts and typography settings.

**Comment by rdzhaoxin** [comment]
@BradleyGBrandt I'm very sorry to bring you a bad experience. What is your IDEA version?

**Comment by rdzhaoxin** [comment]
<img width="1260" alt="image" src="https://github.com/rdzhaoxin/bionic-reading-docs/assets/35715627/4d56cd9e-d0f5-4822-b334-ed7140fee374">
IntelliJ IDEA 2023.1.3 (Ultimate Edition)
@BradleyGBrandt 
I tested it and it works fine in IDEA 2023.1.3. Are you using CLion?
